---
galaxy_info:
  author: Prakhar Srivastava
  description: OpenShift Lightspeed demo content (RHEL9 VM, RAG integration, broken pod)
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: '2.9'
  platforms:
  - name: Fedora
    versions:
    - all
  galaxy_tags:
  - openshift
  - virtualization
  - lightspeed
  - rag
  - demo

dependencies: []
