---
galaxy_info:
  author: Prakhar Srivastava
  description: Deploy a small RHEL 9 VM for OpenShift Lightspeed demos
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: '2.9'
  platforms:
  - name: Fedora
    versions:
    - all
  galaxy_tags:
  - openshift
  - virtualization
  - demo

dependencies: []
